plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/sunz/.openclaw/workspace/all-banana-cake"
publishOrigin = "config"
command = "echo 'No build needed'"
commandOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]